_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    pt-br: pt-br
  domains:
    en: ''
    es: ''
    pt-br: ''
selected_langcode: site_default
